name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Build
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: needed_but_not_used_for_builds

      - name: Test
        run: make test
